### ISSUE TITLE
Source code function

### ISSUE THREAD

**Issue by haofanglee** [Aharoni-Lab/Miniscope-DAQ-Cypress-firmware#9]
Hello there! I'm trying to debug a DAQ board that we built using the firmware source code. I couldn't locate function CyU3PDeviceInit()  and CyU3PDevice ConfigureIOMatrix(). Do you know where to find them? Thank you!

**Comment by daharoni** [comment]
Hi, I think these are calls to some embedded Cypress functions that exist in the Cypress libraries. I don't know if they give you direct access to the source code of these functions.
